server :
  port : 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/user_db
    password: 1*2*3*4*5*6*you

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

